# Generated by Django 3.1.4 on 2020-12-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20201212_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='code',
            field=models.IntegerField(verbose_name='Semester Code'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='display_name',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
    ]
