# Generated by Django 3.1.4 on 2020-12-13 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_post_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='course.semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='course.course'),
        ),
    ]
