# Generated by Django 3.1.4 on 2020-12-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_picture_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='books',
            field=models.ManyToManyField(related_name='posts', to='course.Book'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pictures',
            field=models.ManyToManyField(related_name='questions', to='course.Picture'),
        ),
    ]
