# Generated by Django 3.1.4 on 2020-12-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, default='title not found', max_length=500, null=True),
        ),
    ]
