# Generated by Django 3.1.4 on 2020-12-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20201216_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='media/pictures'),
        ),
    ]
