# Generated by Django 3.1.4 on 2020-12-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_classnote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='file',
        ),
        migrations.AddField(
            model_name='classnote',
            name='title',
            field=models.CharField(blank=True, default='title not found', max_length=500, null=True),
        ),
    ]
