# Generated by Django 3.1.4 on 2020-12-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20201218_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='classnotes',
            field=models.ManyToManyField(blank=True, related_name='posts', to='course.ClassNote'),
        ),
    ]
