# Generated by Django 3.1.4 on 2020-12-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_post_classnotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='posts', to='course.Question'),
        ),
    ]
