# Generated by Django 3.1.4 on 2020-12-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20201219_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='course_teacher',
            field=models.CharField(default='Course Teacher Not Assigned', max_length=100),
        ),
    ]
