export const SEMESTER_DATA_LOADED = "SEMESTER_DATA_LOADED";
export const SEMESTER_DATA_ERROR = "SEMESTER_DATA_ERROR";
export const SEMESTER_DATA_LOADING = "SEMESTER_DATA_LOADING";

export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR";
export const AUTH_LOADING = "AUTH_LOADING";
export const FORGET_PASSWORD_RESET_EMAIL_SENT = "FORGET_PASSWORD_RESET_EMAIL_SENT";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const RESET_PASSWORD_STATUS = "RESET_PASSWORD_STATUS";

export const COURSE_DATA_LOADED = "COURSE_DATA_LOADED";
export const COURSE_DATA_LOAD_ERROR = "COURSE_DATA_LOAD_ERROR";
export const COURSE_CREATED = "COURSE_CREATED";
export const COURSE_CREATE_ERROR = "COURSE_CREATE_ERROR";

export const POST_DATA_LOADING = "POST_DATA_LOADING";
export const POST_DATA_LOADED = "POST_DATA_LOADED";
export const POST_DATA_LOAD_ERROR = "POST_DATA_LOAD_ERROR";
export const POST_CREATED = "POST_CREATED";
export const POST_CREATE_ERROR = 'POST_CREATE_ERROR';
export const POST_CREATE_LOADING = 'POST_CREATE_LOADING';