export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const ALL_SEMESTER_DATA_LOADED = "ALL_SEMESTER_DATA_LOADED";
export const ALL_SEMESTER_DATA_ERROR = "ALL_SEMESTER_DATA_ERROR";
export const COURSE_CREATED = "COURSE_CREATED";
export const COURSE_CREATE_ERROR = "COURSE_CREATE_ERROR";
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
export const USER_LOGGED_OUT= 'USER_LOGGED_OUT'
export const USER_LOGOUT_ERROR= 'USER_LOGOUT_ERROR'