export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const ALL_SEMESTER_DATA_LOADED = "ALL_SEMESTER_DATA_LOADED";
export const ALL_SEMESTER_DATA_ERROR = "ALL_SEMESTER_DATA_ERROR";
export const COURSE_CREATED = "COURSE_CREATED";
export const COURSE_CREATE_ERROR = "COURSE_CREATE_ERROR";
