# Generated by Django 3.1.4 on 2020-12-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reg_no',
            field=models.IntegerField(default=2017338051, unique=True),
            preserve_default=False,
        ),
    ]
