# Generated by Django 3.1.4 on 2020-12-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reg_no',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
