# Generated by Django 3.1.4 on 2020-12-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201217_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='reg_no',
        ),
    ]
